### ISSUE TITLE
Error while running tests - Unable to spawn isolate: The built-in library 'dart:html' is not available on the stand-alone VM

### ISSUE THREAD

**Issue by arun-sahadevan** [leerob/dart-react-todo#1]
I tried running the entire test suite by command :

`pub run test --pub-serve=8081 test/unit/generated_runner_test.dart`
Not getting any error , but showing no tests ran . 

![capture5](https://user-images.githubusercontent.com/39547347/41893884-cf9f2384-793a-11e8-9de0-4e3f12613f99.PNG)

I guess the command i used is correct . Please correct me if am wrong . 

@leerob @leerobinson-wf

**Comment by leerobinson-wf** [comment]
Try this command: `export DARTIUM_EXPIRATION_TIME=1577836800; pub run dart_dev test`

You can also add it as an alias in your bash profile
```sh
alias test="export DARTIUM_EXPIRATION_TIME=1577836800; pub run dart_dev test"
```

Reference: https://github.com/dart-lang/sdk/issues/33580

**Comment by arun-sahadevan** [comment]
I am not using Dartium. Using VS Code and Chrome fro testing. Its throwing error on giving this command

**Comment by arun-sahadevan** [comment]
Even on trying to run command **pub run test** , its throwing error . : 

![image](https://user-images.githubusercontent.com/39547347/42617248-ab32a0fc-85ce-11e8-96ae-3c24d6234564.png)


Please anyone provide me the correct command to run tests??? 
@leerob @leerobinson-wf

**Comment by leerobinson-wf** [comment]
You should be using the command `pub run dart_dev test` (or `ddev test` if you have the alias), not `pub run test`. Could you give that a shot?

**Comment by leerob** [comment]
I'm going to be re-writing this for Dart 2.0, so I'm going to close out old issues.
