### ISSUE TITLE
ddev test command not recognised

### ISSUE THREAD

**Issue by arun-sahadevan** [leerob/dart-react-todo#2]
As per your documentation , **ddev test** command is not working for testing . 

![image](https://user-images.githubusercontent.com/39547347/42617053-01715e00-85ce-11e8-8364-745cc42aa582.png)

**Comment by leerobinson-wf** [comment]
Have you set up this alias? `$ alias ddev='pub run dart_dev'`

It looks like you're on Windows, which I haven't explicitly tested, but that should work. After setting up the alias, then you can do `ddev test`. You could also just run `pub run dart_dev test` which is the same thing.

**Comment by arun-sahadevan** [comment]
Thanks for the reply . I tried running the command `pub run dart_dev test` > But some other error.

![capture](https://user-images.githubusercontent.com/39547347/42861315-19896a2e-8a78-11e8-880b-89ad07537e34.PNG)

**Comment by leerob** [comment]
I'm going to be re-writing this for Dart 2.0, so I'm going to close out old issues.
